version: "3.4"

services:
  ai-inference:
    build: .
    container_name: "sdg-server-ai-inference"
    restart: unless-stopped
    logging:
      options: 
        max-size: '2m'
        max-file: '10'
    networks:
      - default

networks:
  default:
    external: 
      name: gateway
